trigger:
- master

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'azzkacr'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'azzkrg'
    azureResourceGroup: 'kubelab'
    kubernetesCluster: 'privateaks'
    command: 'apply'
    arguments: '-f vote-app.yaml'