trigger:
- master

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'azzkrg'
    azureResourceGroup: 'kubelab'
    kubernetesCluster: 'privateaks'
    command: 'apply'
    arguments: '-f vote-app.yaml'